main/urls.py
from django.conf.urls import url

from main.views import generic
from main.views import webhooks


urlpatterns = [
    url(r'^$', generic.home, name="home"),
    url(r'^conversations/(?P<conversation_id>[^/]*)/$', generic.conversation_view, name="conversation-view"),
    url(r'^conversations/(?P<conversation_id>[^/]*)/delete/$', generic.conversation_delete, name="conversation-delete"),
    url(r'^conversations/(?P<conversation_id>[^/]*)/change/$', generic.conversation_change, name="conversation-change"),
]

urlpatterns += [
    url(r'^webhooks/forwarded/$', webhooks.forwarded, name="forwarded-webhook"),
    url(r'^webhooks/email/$', webhooks.email, name="email-webhook"),
    url(r'^webhooks/cron/$', webhooks.cron, name="cron-webhook"),
]

spamnesty/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^entrary/', admin.site.urls),
    url(r'^', include('main.urls', namespace="main")),
    url(r'^', include('classification.urls', namespace="classification")),
]


def handler500(request):
    from django.template import RequestContext, loader
    from django.http import HttpResponseServerError

    content_type = request.META.get('HTTP_ACCEPT', request.META.get('CONTENT_TYPE', 'text/html')).lower()
    if content_type == "application/json":
        return HttpResponseServerError(
                '{"result": "error", "error_msg": "There was a server error. Please try again later."}',
                content_type='application/json'
                )

    t = loader.get_template('500.html')
    return HttpResponseServerError(t.render(RequestContext(request, {})))

main/models.py
from __future__ import unicode_literals

import datetime
import re
import random
import time

import shortuuid
from django.conf import settings
from django.core.mail import EmailMessage
from django.db import models
from django.db.utils import IntegrityError
from django.urls import reverse
from email.utils import make_msgid
from faker import Faker

from .utils import parse_forwarded_message, parse_email_address


def generate_message_id(domain_name) -> str:
    "Generate an email message ID."
    return make_msgid(domain=domain_name)


def generate_fake_name():
    "Generate a fake name."
    fake = Faker()
    fake.seed(time.time())
    return fake.name()


def generate_key() -> str:
    "Generate a secret key for an object."
    return shortuuid.ShortUUID().random()


def generate_uuid() -> str:
    "Generate a UUID for an object."
    return shortuuid.ShortUUID("abdcefghjkmnpqrstuvwxyz").random()[:8]


def get_default_category() -> int:
    "Retrieve the default SpamCategory"
    return SpamCategory.objects.get(default=True).id


def get_random_domain():
    "Choose a random domain from the database."
    return Domain.objects.order_by("?").first()


class CharIDModel(models.Model):
    """Base model that gives children string IDs."""
    id = models.CharField(max_length=30, primary_key=True,
            default=generate_uuid, editable=False)

    class Meta:
        abstract = True


class Domain(CharIDModel):
    "A domain to use for sending and receiving email."
    # The domain name (e.g. example.com).
    name = models.CharField(max_length=1000)
    # The company name (e.g. Example, LLC).
    company_name = models.CharField(max_length=1000)

    def __str__(self):
        return "{0.company_name} ({0.name})".format(self)


class SpamCategory(CharIDModel):
    """The categories of spam emails."""
    name = models.CharField(max_length=30)
    default = models.BooleanField(default=False, db_index=True)

    class Meta:
        verbose_name_plural = "spam categories"

    def __str__(self):
        return self.name


class ReplyTemplate(CharIDModel):
    """Custom reply templates."""
    body = models.TextField()
    category = models.ForeignKey(SpamCategory, default=get_default_category)

    @property
    def snippet(self):
        "Get the first few characters of the reply."
        return self.body[:40]

    def __str__(self):
        return self.snippet


class ConversationManager(models.Manager):
    def create(self, *args, **kwargs):
        """Generate an object, retrying if there's an ID collision."""

        # Try to generate new IDs for the object if one collides.
        tries = 10
        for x in range(tries):
            try:
                obj = super().create(*args, **kwargs)
            except IntegrityError:
                continue
            else:
                break
        else:
            raise IntegrityError("Could not find an ID after %s tries." % tries)

        return obj

    def get_by_message(self, message):
        """
        Accept a message and try to discover the conversation it belongs to.

        Return an existing Conversation instance, if the message is a reply to
        one of the messages we've already seen, or a new Conversation instance
        if the message is new or has just been forwarded.

        The message instance that is passed in need not be saved or have a
        conversation property set, although it should have the in_reply_to
        property set, if possible.
        """
        if message.direction == "F":
            # A forwarded email gets a new conversation.
            conversation = self.create()
        else:
            replied_to = Message.objects.filter(message_id=message.in_reply_to).first()
            if not replied_to:
                # There may not be an included in-reply-to header, check the
                # email address.
                conversation = Conversation.objects.filter(sender_email=message.recipient_email).first()
                if not conversation:
                    # We've never seen this ID before, so return a new conversation.
                    conversation = super().create()
            else:
                # If we've seen a message with that ID before, return its
                # conversation.
                conversation = replied_to.conversation
        return conversation


class Conversation(CharIDModel):
    """The main conversation object."""
    # The email address of the person who reported this message.
    reporter_email = models.CharField(max_length=1000, blank=True, db_index=True)

    # The name of our sender (the bot).
    sender_name = models.CharField(max_length=1000, default=generate_fake_name)

    # The email address of the bot (so we can match incoming messages).
    sender_email = models.CharField(max_length=1000, blank=True, db_index=True)

    # The secret key for editing the conversation.
    secret_key = models.CharField(max_length=1000, default=generate_key)

    # The fake domain to use to send mail from.
    domain = models.ForeignKey(Domain, default=get_random_domain)

    # The category of the email (sales, scam, dating, etc).
    category = models.ForeignKey(SpamCategory, default=get_default_category)

    # Whether this has been classified by a trusted human.
    classified = models.BooleanField(default=False, db_index=True)

    objects = ConversationManager()

    def __str__(self):
        return "%s <%s>" % (self.sender_name, self.sender_email)

    def get_absolute_url(self):
        return reverse("main:conversation-view", args=[self.id])

    @property
    def messages(self):
        """
        A QuerySet of all the messages in this converation, sorted by
        ascending date (most recent last).
        """
        return self.message_set.all().order_by("timestamp")

    @property
    def calculated_sender_username(self):
        "Derive a username from the sender's name."
        split_name = self.sender_name.split()
        return (split_name[0][0] + split_name[1]).lower()

    @property
    def calculated_sender_email(self):
        "Derive a username from the sender's username."
        return "%s@%s" % (self.calculated_sender_username, self.domain.name)

    def save(self, *args, **kwargs):
        "Generate the sender_email on saving."
        if not self.sender_email:
            self.sender_email = self.calculated_sender_email

        super().save(*args, **kwargs)


class Message(CharIDModel):
    """A single email message."""
    DIRECTIONS = [("F", "Forwarded"), ("S", "Sent"), ("R", "Received")]

    timestamp = models.DateTimeField(auto_now_add=True)
    conversation = models.ForeignKey(Conversation)

    # Whether this email was forwarded to us, sent by us, or received by us from
    # the spammer.
    direction = models.CharField(choices=DIRECTIONS, max_length=10)

    sender = models.CharField(max_length=1000, blank=True)
    recipient = models.CharField(max_length=1000, blank=True)
    subject = models.CharField(max_length=1000)

    # The time to send the email on.
    send_on = models.DateTimeField(blank=True, null=True)

    # The plaintext body of the email.
    body = models.TextField()

    # Any quoted text we need to include in the message.
    quoted_text = models.TextField(blank=True)

    # The stripped body of the email (no signature).
    stripped_body = models.TextField(blank=True)

    # The message ID, so we can keep track of the conversation.
    message_id = models.CharField(max_length=1000, unique=True)

    # The in-reply-to header, which complements the ID.
    in_reply_to = models.CharField(max_length=1000, blank=True)

    class Meta:
        ordering = ["timestamp"]

    def __str__(self):
        return self.subject

    def get_absolute_url(self):
        return reverse("main:conversation-view", args=[self.conversation.id])

    @property
    def sender_name(self):
        "Parse and return the sender's name."
        if not self.sender:
            return ""
        return parse_email_address(self.sender)[0]

    @property
    def sender_email(self):
        "Parse and return the sender's email address."
        if not self.sender:
            return ""
        return parse_email_address(self.sender)[1]

    @property
    def recipient_name(self):
        "Parse and return the recipient's name."
        if not self.recipient:
            return ""
        return parse_email_address(self.recipient)[0]

    @property
    def recipient_email(self):
        "Parse and return the recipient's email address."
        if not self.recipient:
            return ""
        return parse_email_address(self.recipient)[1]

    @property
    def best_body(self):
        """
        Return the best body to use (i.e. stripped_body if available).
        """
        return self.stripped_body or self.body

    @classmethod
    def parse_from_mailgun(cls, posted, forwarded=False):
        """
        Parse a message from Mailgun and return a Message instance.
        """
        # Delete old messages with this ID, as it probably means the server
        # crashed on them and we need to redo whatever we did.
        cls.objects.filter(message_id=posted["Message-Id"]).delete()

        message = cls()
        message.direction = "F" if forwarded else "R"
        message.sender = posted["From"]
        message.recipient = posted["To"]
        message.subject = posted["Subject"]
        message.body = posted["body-plain"]
        message.stripped_body = posted.get("stripped-text", "")
        message.message_id = posted["Message-Id"]
        message.in_reply_to = posted.get("In-Reply-To", "")

        if forwarded:
            # If a message has been forwarded to us, we need to:
            #
            # 1. Store the original reporter's email in the conversation, so we
            #    can email them.
            # 2. Parse the forwarded message from the email and replace the body
            #    of the email with it.

main/views/generic.py
from annoying.decorators import render_to
from django.db.models import Max, Count
from django.contrib import messages
from django.conf import settings
from django.shortcuts import get_object_or_404, redirect
from django.utils.crypto import constant_time_compare
from django.views.decorators.http import require_POST

from ..models import Conversation, SpamCategory


@render_to("home.html")
def home(request):
    if not (request.get_host().startswith("spa.") or settings.DEBUG):
        return {"TEMPLATE": "fake.html"}
    conversations = Conversation.objects.annotate(
            last_message_time=Max('message__timestamp'),
            num_messages=Count("message"),
        ).filter(num_messages__gt=7).order_by('-last_message_time')
    return {"conversations": conversations}


@require_POST
def conversation_delete(request, conversation_id):
    conversation = get_object_or_404(Conversation, pk=conversation_id)
    if constant_time_compare(request.GET.get("key"), conversation.secret_key) or request.user.is_staff:
        messages.success(request, "The conversation has been deleted.")
        conversation.delete()
    else:
        messages.error(request, "The conversation's secret key was invalid.")
    return redirect("main:home")


def conversation_change(request, conversation_id):
    conversation = get_object_or_404(Conversation, pk=conversation_id)
    category = get_object_or_404(SpamCategory, pk=request.GET.get("category", ""))
    if constant_time_compare(request.GET.get("key"), conversation.secret_key) or request.user.is_staff:
        messages.success(request, "The conversation's category has been changed.")
        conversation.category = category
        conversation.classified = request.user.is_staff
        conversation.save()
    else:
        messages.error(request, "The conversation's secret key was invalid.")
    return redirect(conversation)


@render_to("conversation_view.html")
def conversation_view(request, conversation_id):
    conversation = get_object_or_404(Conversation, pk=conversation_id)
    own_conversation = constant_time_compare(request.GET.get("key"), conversation.secret_key)

    if own_conversation and "@" in conversation.reporter_email:
        other_conversations = Conversation.objects.filter(reporter_email=conversation.reporter_email)
    else:
        other_conversations = []

    # Sort with the default category being last.
    categories = SpamCategory.objects.order_by("default", "name")
    return {
        "conversation": conversation,
        "own": own_conversation,
        "spam_categories": categories,
        "other_conversations": other_conversations,
    }

main/views/webhooks.py
import datetime

from django.core.mail import EmailMessage
from django.http import HttpResponse
from django.template.loader import render_to_string
from django.views.decorators.csrf import csrf_exempt

from raven.contrib.django.raven_compat.models import client

from ..models import Message
from ..utils import construct_reply


@csrf_exempt
def forwarded(request):
    "The webhook that fires when a user forwards a legitimate email."

    if not request.POST.get("From"):
        return HttpResponse("Empty sender.")

    if Message.objects.filter(message_id=request.POST.get("Message-Id", "")).exists():
        # Ignore Mailgun retries if we've already added the message.
        return HttpResponse("OK")

    # Try to parse the forwarded message.
    try:
        message = Message.parse_from_mailgun(request.POST, forwarded=True)
    except:
        # Notify Sentry.
        client.captureException()
        message = None

    if not message:
        # Notify the sender that we couldn't find the spammer's address.
        EmailMessage(
            subject=render_to_string(
                "emails/forward_no_email_subject.txt",
                request=request
            ).strip(),
            body=render_to_string(
                "emails/forward_no_email_body.txt",
                request=request
            ),
            to=[request.POST["From"]],
        ).send()
    else:
        # Notify the sender that we've received it.
        EmailMessage(
            subject=render_to_string(
                "emails/forward_received_subject.txt",
                request=request
            ).strip(),
            body=render_to_string(
                "emails/forward_received_body.txt",
                context={"message": message},
                request=request
            ),
            to=[request.POST["From"]],
        ).send()

        # Reply to the spammer.
        reply = construct_reply(message)
        reply.send()

    return HttpResponse("OK")


@csrf_exempt
def email(request):
    "The webhook that fires when we get some spam."

    # Parse the received message.
    message = Message.parse_from_mailgun(request.POST)

    # If there is no unsent message in the queue, queue one.
    if not message.conversation.messages.exclude(send_on=None).exists():
        # Reply to the spammer.
        reply = construct_reply(message)
        reply.queue()

    return HttpResponse("OK")


@csrf_exempt
def cron(request):
    "The webhook that is called when it's time to send emails."
    unsent_messages = Message.objects.exclude(send_on=None).filter(send_on__lt=datetime.datetime.now())
    for message in unsent_messages:
        message.send()

    return HttpResponse("OK")

main/templates/base.html
{% load staticfiles bootstrap3 %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>{{ request.site.name }} - {% block title %}{% endblock %}</title>

        <link rel="stylesheet" href="https://opensource.keycdn.com/fontawesome/4.7.0/font-awesome.min.css" crossorigin="anonymous">

        <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
        <link href="{% static "css/style.css" %}" rel="stylesheet">

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
        {% block scripts %}
        {% endblock %}
    </head>
    <body>
        {% if not settings.DEBUG %}
        <script>
            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
            })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

            ga('create', 'UA-51110-28', 'auto');
            ga('send', 'pageview');

        </script>
        {% endif %}

        <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="/">{{ request.site.name }}</a>
                <p class="navbar-text">Fun with spam!</p>
            </div>

            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    {% if other_conversations %}
                    <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Your conversations <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        {% for conversation in other_conversations %}
                        <li>
                        <a href="{% url "main:conversation-view" conversation.id %}">The colloquy of {{ conversation.sender_name }}</a>
                        </li>
                        {% endfor %}
                    </ul>
                    </li>
                    {% endif %}

                    {% if request.user.is_authenticated %}
                    <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url "admin:index" %}">Admin</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="{% url "admin:logout" %}">Logout</a></li>
                    </ul>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
        </nav>

        <div class="container">
            {% bootstrap_messages %}

            {% block content %}
            {% endblock %}
        </div>

        <!-- {{ settings.COMMIT_HASH }} -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    </body>
</html>

main/templates/conversation_view.html
{% extends "base.html" %}

{% block title %}The colloquy of {{ conversation.sender_name }}{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <h3>The colloquy of {{ conversation.sender_name }}</h3>
        <p>
        Someone forwarded a spammer's email to {{ request.site.name }}, which
        replied to the email, pretending to be a person called
        {{ conversation.sender_name }} and starting a conversation.
        </p>

        <p>
        This is that conversation.
        </p>

        {% if request.user.is_staff %}
        <a class="btn btn-default" href="{% url "admin:main_conversation_change" conversation.id %}">Admin</a>
        {% endif %}

        {% if own or request.user.is_staff %}
        <div class="btn-group">
            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {{ conversation.category }} <span class="caret"></span>
            </button>
            <ul class="dropdown-menu">
                <li class="disabled"><a href="#">Select the category of the spam email</a></li>
                <li role="separator" class="divider"></li>
                {% for category in spam_categories %}
                <li><a href="{% url "main:conversation-change" conversation.id %}?key={{ request.GET.key }}&category={{ category.id }}">{{ category.name }}</a></li>
                {% endfor %}
            </ul>
        </div>

        <form method="POST" style="display: inline" action="{% url "main:conversation-delete" conversation.id %}?key={{ request.GET.key }}">{% csrf_token %}
            <button type="submit" class="btn btn-danger">Delete</button>
        </form>
        {% endif %}
    </div>
    <div class="col-md-12">
        <hr>
    </div>
</div>

{% for message in conversation.message_set.all %}
    <div class="row">
        {% if message.direction == "S" %}
        <div class="col-md-4"></div>
        {% endif %}

        <div class="col-md-8">
            {% if message.direction == "S" %}
            <div class="panel panel-default panel-success">
                <div class="panel-heading">
                    <h3 class="panel-title">{{ request.site.name }}</h3>

            {% else %}
            <div class="panel panel-default panel-danger">
                <div class="panel-heading">
                    <h3 class="panel-title">Spammer</h3>
            {% endif %}
                </div>
                <ul class="list-group">
                    <li class="list-group-item"><strong>Subject:</strong> {{ message.subject }}</li>
                    <li class="list-group-item"><strong>On:</strong> {{ message.timestamp }}</li>
                </ul>
                <div class="panel-body">
                    <p>{{ message.best_body|linebreaks }}</p>
                </div>
            </div>
        </div>

        {% if message.direction != "S" %}
        <div class="col-md-4"></div>
        {% endif %}
    </div>
{% endfor %}
</div>
{% endblock %}

main/templates/home.html
{% extends "base.html" %}

{% load cache %}

{% block title %}Home{% endblock %}

{% block content %}
<div class="row">
    <div class="col-xs-12">
        <h2>What is {{ request.site.name }}?</h2>
        <p>{{ request.site.name }} is a way to waste spammers' time. If you get a spam
        email, simply forward it to <strong>sp@mnesty.com</strong>,
        and {{ request.site.name }} will strip your email address, pretend it's a real
        person and reply to the email. Just remember to strip out any personal
        information from the body of the email, as it will be used so the reply looks
        more legitimate.</p>

        <p>That way, the spammer will start talking to a bot, and hopefully waste some
        time there instead of spending it on a real victim. Meanwhile,
        {{ request.site.name }} will send you an email with a link to the conversation,
        so you can watch it unfold live!</p>

        <h3>Current state</h3>
        <p>
        <strong>WARNING:</strong> The service isn't done yet! It looks like crap and
        there may be loads of wonky stuff going on. That said, you can help by
        cautiously using it for a bit, and
        <a href="https://gitlab.com/stavros/Spamnesty/issues">opening an issue</a>
        if you notice something wrong or if you have any suggestions.
        <p>

        <p>
        Thanks for your help!
        </p>

        <p>
        <a class="btn btn-primary" href="https://gitlab.com/stavros/Spamnesty">
            <i class="fa fa-code-fork"></i>
            Fork me on Gitlab
        </a>
        </p>

        <h3>Conversations</h3>
        <div class="row">
            <div class="col-md-12">
                <table class="table">
                    <tr>
                        <th>Person</th>
                        <th>Subject</th>
                        <th>Date</th>
                        <th>Msgs</th>
                    </tr>

                    {% cache 1800 home-conversations %}
                    {% for conversation in conversations %}
                    <tr>
                        <td><a href="{% url "main:conversation-view" conversation.id %}">{{ conversation.sender_name }}</a></td>
                        <td>{{ conversation.message_set.first.subject }}</td>
                        <td>{{ conversation.last_message_time|date:"d M Y" }}</td>
                        <td>{{ conversation.num_messages}}</td>
                    </tr>
                    {% endfor %}
                    {% endcache %}
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}