classification/urls.py
from django.conf.urls import url

from classification.views import classify

urlpatterns = [
    url(r'^classify/$', classify, name="classify"),
]

main/urls.py
from django.conf.urls import url

from main.views import generic
from main.views import webhooks


urlpatterns = [
    url(r'^$', generic.home, name="home"),
    url(r'^conversations/(?P<conversation_id>[^/]*)/$', generic.conversation_view, name="conversation-view"),
    url(r'^conversations/(?P<conversation_id>[^/]*)/delete/$', generic.conversation_delete, name="conversation-delete"),
    url(r'^conversations/(?P<conversation_id>[^/]*)/change/$', generic.conversation_change, name="conversation-change"),
]

urlpatterns += [
    url(r'^webhooks/forwarded/$', webhooks.forwarded, name="forwarded-webhook"),
    url(r'^webhooks/email/$', webhooks.email, name="email-webhook"),
    url(r'^webhooks/cron/$', webhooks.cron, name="cron-webhook"),
]

spamnesty/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^entrary/', admin.site.urls),
    url(r'^', include('main.urls', namespace="main")),
    url(r'^', include('classification.urls', namespace="classification")),
]


def handler500(request):
    from django.template import RequestContext, loader
    from django.http import HttpResponseServerError

    content_type = request.META.get('HTTP_ACCEPT', request.META.get('CONTENT_TYPE', 'text/html')).lower()
    if content_type == "application/json":
        return HttpResponseServerError(
                '{"result": "error", "error_msg": "There was a server error. Please try again later."}',
                content_type='application/json'
                )

    t = loader.get_template('500.html')
    return HttpResponseServerError(t.render(RequestContext(request, {})))

classification/views.py
from annoying.decorators import render_to
from django.http import Http404
from django.shortcuts import get_object_or_404
from django.views.decorators.http import require_http_methods

from main.models import Conversation, SpamCategory


@require_http_methods(["GET", "POST"])
@render_to("classify.html")
def classify(request):
    """
    Allow staff to classify conversations into categories.
    """
    if not request.user.is_staff:
        raise Http404

    if request.method == "POST":
        conversation = get_object_or_404(Conversation, pk=request.POST.get("conversation_id"))
        category = get_object_or_404(SpamCategory, pk=request.POST.get("category_id", ""))
        conversation.category = category
        conversation.classified = True
        conversation.save()
        return {"result": "success"}
    else:
        conversations = Conversation.objects.filter(classified=False)
        conv_count = Conversation.objects.count()
        progress = int((100.0 * conversations.count()) / conv_count) if conv_count else 100

        categories = SpamCategory.objects.all()
        return {
            "conversations": conversations[:10],
            "spam_categories": categories,
            "progress": progress,
        }

classification/templates/classify.html
{% extends "base.html" %}

{% block title %}Conversation classification{% endblock %}

{% block scripts %}
<script>
function classifyConversation(conversation_id, category_id, category_name) {
    var data = new FormData();
    data.append('conversation_id', conversation_id);
    data.append('category_id', category_id);
    data.append('csrfmiddlewaretoken', '{{ csrf_token }}');

    var xhr = new XMLHttpRequest();
    xhr.open('POST', '{% url "classification:classify" %}', true);
    xhr.onload = function () {};
    xhr.send(data);

    document.getElementsByClassName("conv-" + conversation_id)[0].innerHTML =
        category_name + '<span class="caret"></span>';
}
</script>
{% endblock %}

{% block content %}
<div class="row">

    <div class="col-xs-12">
        <h2>Classify conversations</h2>
        <p>
        Please select the appropriate category for each conversation. You can
        change a conversation's classifications, but if you reload the page
        after classifying, the conversation won't show up. So, double-check that
        you've picked the correct category before navigating away.
        </p>

        <div class="progress">
            <div class="progress-bar progress-bar-info progress-bar-striped" role="progressbar" aria-valuenow="{{ progress }}" aria-valuemin="0" aria-valuemax="100" style="width: {{ progress }}%">
                <span class="sr-only">20% Complete</span>
            </div>
        </div>

        <table class="table">
            <tr>
                <th>Message</th>
                <th>Actions</th>
            </tr>

            {% for conversation in conversations %}
            <tr>
                <td>{{ conversation.messages.first.best_body|linebreaksbr }}</td>
                <td>
                    {% if request.user.is_staff %}
                    <p><a class="btn btn-danger" href="{% url "admin:main_conversation_change" conversation.id %}">Admin</a></p>
                    {% endif %}

                    <div class="btn-group">
                        <button type="button" class="btn btn-default dropdown-toggle conv-{{ conversation.id }}" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {{ conversation.category }} <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu">
                            <li class="disabled"><a href="#">Select the category of the spam email</a></li>
                            <li role="separator" class="divider"></li>
                            {% for category in spam_categories %}
                            <li><a href="#" onclick="classifyConversation('{{ conversation.id }}', '{{ category.id }}', '{{ category.name }}'); return false;">{{ category.name }}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>
</div>
{% endblock %}